# Generated by Django 6.0.7 on 2026-09-05 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="entry_year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1390),
                    django.core.validators.MaxValueValidator(1420),
                ]
            ),
        ),
    ]
